# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of the knapsack problem
#' @param x A data frame with two variables (w, v) that contains the weight (w) and value (v) of each item.
#' @param W The knapsack capacity.
knapsack_cpp <- function(x, W) {
    .Call('_lab6package_knapsack_cpp', PACKAGE = 'lab6package', x, W)
}

